---
- name: Ensure Apache web server is installed and running
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Ensure apache webserver is installed"
      yum:
        name: httpd
        state: present

    - name: "Ensure apache webserver is started"
      service:
        name: httpd
        state: started
