---
- name: Ensure Apache web server is installed and running
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Ensure apache webserver and firewalld is installed"
      yum:
        name: 
          - httpd
          - firewalld
        state: present
        
    - name: "Ensure firewalld is started"
      service:
        name: firewalld
        state: started

    - name: "Ensure firewall openings are in place."
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: "Ensure apache webserver is started"
      service:
        name: httpd
        state: started
