- name: Create namespace in OpenShift
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: "{{ thenamespace }}"
        api_version: v1
        kind: Namespace
        state: present
