- name: Create namespace in OpenShift
  hosts: localhost
  tasks:
    - name: debug
      command: pwd
    - name: debug again
      command: ls -la
    - name: Create a k8s namespace
      k8s:
        name: "{{ thenamespace }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/ec2-user/.kube/config
