- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/ec2.yaml
  tasks:
  - name: Ensure a security group for VM systems is in place
    ec2_group:
      name: "{{ ec2_security_group_vm_systems }}"
      description: Security Group for VMs
      region: "{{ ec2_region }}"
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Provision the systems which are to be managed with Ansible
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      key_name: "{{ec2_key}}"
      region: "{{ ec2_region }}"
      group: "{{ ec2_security_group_vm_systems }}"
      instance_type: t2.micro
      image: "{{ ec2_ami_id }}"
      wait: true
      exact_count: "{{ ec2_number_of_vm }}"
      count_tag:
        identity: "{{ ec2_identity_tag }}"
      instance_tags:
        identity: "{{ ec2_identity_tag }}"
