---
# tasks file for tomcat

- name: loop over tomcat_instances
  ansible.builtin.include_tasks:
    file: instance.yml
  loop: "{{ tomcat_instances }}"
  loop_control:
    label: "{{ instance.name }}"
    loop_var: instance
  when:
    - tomcat_instances is defined
