---
# tasks file for service

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install required packages
  ansible.builtin.package:
    name: "tomcat8"
    state: present
  notify:
    - gather facts

- name: Start Tomcat application server
  service:
    name: "tomcat8"
    state: started
    enabled: yes

- name: flush handlers
  ansible.builtin.meta: flush_handlers
